### ISSUE TITLE
Brightness not work for me

### ISSUE THREAD

**Issue by 0xgobag** [Human7900/macOS-HP-Probook-430-G3-Resources#5]
hy, I use your efi because my laptop type same with your laptop, I get problem, when I turn on my laptop brightness slide not work (brightness up and down ). but when after sleep brightness work perfectly, can u help me to fix ?

**Comment by Human79** [comment]
Hi mate,
I would like to help you however I need some information-
1. Can you confirm your specs?
2. Are you using my latest EFi?
3. Which laptop is this?

Regards.
~Human7900.

**Comment by 0xgobag** [comment]
1. Can you confirm your specs?

- Processore : Intel Core i5-6200U
- iGPU : Intel HD Graphics 520
- RAM : 1x 8GB + 1x 4 GB DDR 3
- Audio Codec : Conexant Audio
- Trackpad : Synaptitics
- Storage : Vgen SSD-NvME 256GB + WD 1TB
- Wirelless LAN : Intel Dual Band Wireless-AC 8260 802.11a/b/g/n/ac (2x2) Wi-Fi and Bluetooth 4.2 Combo
- Ethernet : Realtek RTL8168H/8111H
- OS Version : Bigsur

2. Are you using my latest EFi?

Yes im use your latest EFI


3. Which laptop is this?

My laptop is HP Probook 430 G3

can you help me ?

**Comment by Human79** [comment]
Do you have windows installed?

**Comment by 0xgobag** [comment]
Yes i have windows 11 installed

**Comment by Human79** [comment]
I need a screenshot from `Device Manager -> Display Adapters -> Properties -> Details > BIOS device name`.

**Comment by 0xgobag** [comment]
In windows ? I see GFX0, but wait i can attach the screenshoot

**Comment by Human79** [comment]
Please attach the screenshot.

**Comment by 0xgobag** [comment]
![image](https://user-images.githubusercontent.com/15613333/128484622-10408a12-0b77-456b-8040-a4fc17865792.png)

this screenshoot

**Comment by Human79** [comment]
Hi,
I will be updating the Brightness SSDT with OpenCore 0.7.2 update.
Please test that and report back.
Regards.
~Human7900

**Comment by 0xgobag** [comment]
I can wait for the update and i can test it… ihope my brightness can fix 😊

**Comment by Human79** [comment]
Yeah, I think on Monday, it will be released.

**Comment by 0xgobag** [comment]
Verison 0.7.2 will be support monterey or not ?

**Comment by Human79** [comment]
Even the 0.7.1 version supports Monterey.

**Comment by 0xgobag** [comment]
I will be waiting for new version and fix the brightness

**Comment by Human79** [comment]
Yeah, will be released tomorrow.
Also, can you test HDMI and macOS Monterey?

**Comment by 0xgobag** [comment]
I will be test on monterey, now i can test in big sur

**Comment by Human79** [comment]
Opencore 0.7.2 has been released.

**Comment by 0xgobag** [comment]
Okay i try

**Comment by 0xgobag** [comment]
I try new version, but brightness not work too, work after sleep, same with previous version

**Comment by Human79** [comment]
Please replace the SSDT-PNLF in `EFI>OC>ACPI` with this and report back.
[SSDT-PNLF.aml.zip](https://github.com/Human7900/macOS-HP-Probook-430-G3-Resources/files/6962936/SSDT-PNLF.aml.zip)

**Comment by 0xgobag** [comment]
Not work too, can u see my ioreg ?

**Comment by Human79** [comment]
Did you do some modifications to my EFI?

**Comment by 0xgobag** [comment]
no, I not modify your efi, I try patch EDID too but no successfully.

**Comment by Human79** [comment]
Are you using control center or system preferences to adjust the brightness?

**Comment by 0xgobag** [comment]
Using keyboard, control center same not work, did u see my video https://youtu.be/62PU19WrWUU

**Comment by Human79** [comment]
That's weird.
I will give you a efi in some time.

**Comment by Human79** [comment]
Please try this EFI and don't forget to reset nvram before booting.
[EFI.zip](https://github.com/Human7900/macOS-HP-Probook-430-G3-Resources/files/6989838/EFI.zip)

**Comment by 0xgobag** [comment]
same, not working too T.T

can u try this https://www.insanelymac.com/forum/topic/340152-laptop-brightness-not-working-until-sleepwake-cycle-after-changing-lcd-panel/

https://github.com/hieplpvip/AppleBacklightSmoother

**Comment by Human79** [comment]
I have implemented this, please generate your SMBios as MacBookPro 13,1 and Reset Nvram before booting.
Please try and report back.
[EFI.zip](https://github.com/Human7900/macOS-HP-Probook-430-G3-Resources/files/7005105/EFI.zip)

**Comment by 0xgobag** [comment]
I was try
1. put your efi and place in my boatloader
2. generate smbisos to MacBook Pro 13,1
3. boot to oc, reset nvram, reboot and boot to hackintosh

after reboot my brightness still not work, when I'm put slide to left, my screen black, 
after sleep my brightness work perfectly

**Comment by Human79** [comment]
Hi,
Please try this EFI.
Once again, generate your own SMBios as MacBookPro 13,1 and Reset NVRAM before booting.
[EFI.zip](https://github.com/Human7900/macOS-HP-Probook-430-G3-Resources/files/7020809/EFI.zip)

**Comment by 0xgobag** [comment]
> Hi,
> Please try this EFI.
> Once again, generate your own SMBios as MacBookPro 13,1 and Reset NVRAM before booting.
> [EFI.zip](https://github.com/Human7900/macOS-HP-Probook-430-G3-Resources/files/7020809/EFI.zip)

I was try it but still not work

**Comment by Human79** [comment]
Hi,
Once again, please try this EFI, generate your own SMBios as MacBookPro 13,1 and Reset NVRAM before booting.
[EFI.zip](https://github.com/Human7900/macOS-HP-Probook-430-G3-Resources/files/7029025/EFI.zip)

**Comment by 0xgobag** [comment]
Not work bro, no luck

**Comment by Human79** [comment]
Please reinstall macOS and report back with the EFI which is on the repo.
You can try other macOS versions as well.

**Comment by Human79** [comment]
I am closing this issue for now as you are not responding.
This issue will be reopened when you reply back.
